---
# Location:
country: "USA"
state: "CA"
city: "Santa Clara"
site-id: "Lab01"

#Services
domain:
    name: "poc.arista.com"
    vrf: "management"
    server:
        - "8.8.8.8"
        - "8.8.4.4"

ntp:
    src_intf: "mgmt1/1/1" 
    vrf: "management"
    authenticate: "yes"
    auth_key:
      - seq: "1"
        type: "md5"
        text: "lab1234"
      - seq: "2"
        type: "md5"
        text: "dell1234"
    server:
        - addr: "10.10.60.81"
          prefer: "yes"
          state: "present"
        - addr: "10.10.60.82"
          prefer: "no"
          state: "present"
        - addr: "10.10.60.83"
          prefer: "no"
          state: "present"

log:
    src_intf: "mgmt1/1/1" 
    vrf: "management"
    server:
        - addr: "172.100.100.81"
          port: "514"
        - addr: "172.100.100.249"
          port: "514"
aaa:
    authentication: "local group tacacs+"
    authorization: 
    accounting:

aaa_tac:
    timeout: "60" 
    vrf: "management"
    server:
        - addr: "1.1.1.1"
          key: "{{ vault_tac_key }}"
        - addr: "1.1.1.2"
          key: "{{ vault_tac_key }}"

snmp:
    version: "2c"
    vrf: "management"
    contact: "labadmin@poc.arista.com"
    proto_port: "1161" ## leave blank for default 161
    location: "Santa Clara Lab"
    view:
        - name: "globalView"
          oid: "1.3.6.1"
    group:
        - name: "admin01"
          version: "2c"
          view: 
            - name: "view01"
              view_type: "read"
              view_name: "globalView"
            - name: "view02"
              view_type: "write"
              view_name: "globalView"
        - name: "admin02"
          version: "3"
          sec_level:
            - name: "auth"
              view_type: "read"
              view_name: "globalView"
            - name: "priv"
              view_type: "read"
              view_name: "globalView"
    user:
        - name: "netops"
          group: "admin01"
          version: "3"
          passwd: "{{ vault_snmp_labadmin_auth }}"
          auth: "sha"
          encry: "aes"
        - name: "nimsoft"
          version: "3"
          group: "admin01"
          passwd: "{{ vault_snmp_labadmin_auth }}"
          auth: "sha"
          encry: "aes"
    host:
        - addr: "172.100.100.249"
          version: "2c"
          community: "community_01"
        - addr: "99.99.99.99"
          version: "3"
          user: "nimsoft"
          sec_level: "auth"
    community:
        - name: "community_01"
          string: "{{ vault_snmp_comm_ro }}"
          priv: "ro"
          acl: "SNMP-HOSTS"
          group: "admin01"
        - name: "community_02"
          string: "{{ vault_snmp_comm_rw }}"
          priv: "rw"
          acl: "SNMP-HOSTS"
          group: "admin02"

stp:
    mode: "rapid-pvst"
    priority: "8192"
    vlan:
        - id: "3939"
          priority: "8192"

sflow:
  sflow_enable: "true"
  vrf: "mgmt"
  agent_id: "loopback0"
  collector:
    - collector_ip: "172.100.100.249"
      udp_port: 6343
      state: present
  polling_interval: 30
  sample_rate: 1024
  port: "{{ sflow_port_sku }}"

span: "{{ span_sku }}"

telemetry:
  port: "8080"
  auth:
    - password
    - jwt
    - cert
    - none

vrli_vip: 10.60.97.44
no_helper: null
helper_ip: 10.60.97.254

users:
# no including ansible user
    - name: "lab" 
      passwd: "{{ vault_lab_password }}"
      role: "sysadmin"

    - name: "netadmin" 
      passwd: "{{ vault_lab_password }}"
      role: "operator"

oob_ipv4_mask: 24
oob_netv4: 172.100.100.0/24
oob_netv4_gw: 172.100.100.1

lpbk0_netv4: "10.0.0.0/24"
lpbk0_netv6: "2001::/64"

lpbk1_netv4: "10.10.0.0/24"
lpbk1_netv6: "2001:a::/64"

compute_lpbk0_netv4: "10.99.0.0/24"
compute_lpbk0_netv6: "2001:99::/64"

fabric_ptp_netmaskv4: 31
fabric_ptp_netmaskv6: 127
fabric_ptp_netv4: "10.0.1.0/24"
fabric_ptp_netv6: "2001:0:1::/64"

evpn_anycast_vmac: 00:00:00:ff:ff:ff

tor_pair_netmaskv4: 31
tor_pair_netv4: "10.10.{{rack_no}}.0/24"
tor_pair_netv6: "2001:a:{{rack_no}}::/64"
#vlt_mac: 00:00:00:{{rack_no}}{{rack_no}}:{{rack_no}}{{rack_no}}:{{rack_no}}{{rack_no}}
tor_pair_vmac: 00:00:00:{{rack_no}}{{rack_no}}:{{rack_no}}{{rack_no}}:{{rack_no}}{{rack_no}}

v101_netv4: "10.100.1.0/27"
v101_netv6: "2001:100:1::/80"

v104_netv4: "10.104.1.0/27"
v104_netv6: "2001:104:1::/80"

v121_netv4: "10.121.1.0/27"
v121_netv6: "2001:121:1::/80"

v124_netv4: "10.124.1.0/27"
v124_netv6: "2001:124:1::/80"

v141_netv4: "10.141.{{ rack_no }}.0/24"
v141_netv6: "2001:2001:141:{{ rack_no }}::/64"

v142_netv4: "10.142.{{ rack_no }}.0/24"
v142_netv6: "2001:2001:142:{{ rack_no }}::/64"

v201_netv4: "10.100.2.0/27"
v201_netv6: "2001:100:2::/80"

v204_netv4: "10.104.2.0/27"
v204_netv6: "2001:104:2::/80"

v301_netv4: "10.100.3.0/27"
v301_netv6: "2001:100:3::/80"

v304_netv4: "10.104.3.0/27"
v304_netv6: "2001:104:3::/80"

v401_netv4: "99.99.41.0/24"
v401_netv6: "2001:99:41::/64"

v402_netv4: "10.100.42.0/24"
v402_netv6: "2001:100:42::/64"

v403_netv4: "10.100.43.0/24"
v403_netv6: "2001:100:43::/64"
# gw_ptp_netmaskv4: 27
# gw_ptp_netmaskv6: 80
# gw_ptp_netv4: "10.99.1.0/24"
# gw_ptp_netv6: "2001:2001:99::/64"
edge_netmaskv4: 27
edge_netmaskv6: 80
edge_netv4: "10.99.1.0/24"
edge_netv6: "2001:2001:99:1::/64"

# edge01_netv4: "10.99.1.0/24"
# edge01_netv6: "2001:2001:99:1::/64"

# edge02_netv4: "10.99.2.0/24"
# edge02_netv6: "2001:2001:99:2::/64"

k8s_tor_netmaskv4: 24
k8s_tor_netmaskv6: 64
k8s_tor1_netv4: "{{ v141_netv4 }}"
k8s_tor1_netv6: "{{ v141_netv6 }}"
k8s_tor2_netv4: "{{ v142_netv4 }}"
k8s_tor2_netv6: "{{ v142_netv6 }}"

#BGP
spine_asn: "65000"
spine_g1_asn: "65000"
spine_g2_asn: "65000"
rack_tor_asn: "{{ 65000+rack_no }}"
rack01_asn: "65001"
rack02_asn: "65002"
rack03_asn: "65003"
rack04_asn: "65004"
calico_asn: "{{ 65110+rack_no }}"

#Vxlan
lpbk1:
    desc: "Overlay vTEP Endpoint"
    addr_v4: "{{ lpbk1_netv4 | ipaddr(rack_no) | ipaddr('address') }}"

#EVPN iBGP Overlay
evpn_ibgp:
  local_asn: "64999"
  rrs_v4:
    peer_group: evpn_rrs_v4
    addr:
      - "{{ hostvars['leaf07'].lpbk0.addr_v4 }}"
      - "{{ hostvars['leaf08'].lpbk0.addr_v4 }}"
  rrc_v4:
    peer_group: evpn_rrc_v4
    addr:
      - "{{ hostvars['leaf05']['lpbk0']['addr_v4'] }}"
      - "{{ hostvars['leaf06']['lpbk0']['addr_v4'] }}"
  peer_v4:
    peer_group: evpn_rrp_v4
