eth1_desc: "vlan301"
v301_addr_v4: "{{ v301_netv4 | ansible.utils.ipaddr(seq-100) }}"
v301_addr_v6: "{{ v301_netv6 | ansible.utils.ipaddr(seq-100) }}"
v301_gw_v4: "{{ v301_netv4 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
v301_gw_v6: "{{ v301_netv6 | ansible.utils.ipaddr(1) | ansible.utils.ipaddr('address') }}"
v301_routes_v4:
   -
      dst: "{{ compute_lpbk0_netv4 }}"
   -
      dst: "{{ v301_netv4 }}"
   -
      dst: "{{ v201_netv4 }}"
   -
      dst: "{{ v104_netv4 }}"
   -
      dst: "{{ v204_netv4 }}"
v301_routes_v6:
   -
      dst: "{{ compute_lpbk0_netv6 }}"
   -
      dst: "{{ v301_netv6 }}"
   -
      dst: "{{ v201_netv6 }}"
   -
      dst: "{{ v104_netv6 }}"
   -
      dst: "{{ v204_netv6 }}"
