---
- hosts: spine
  connection: httpapi
  gather_facts: no
  collections:
     - dellemc.enterprise_ceos
  tasks:
  - name: Create Interfaces
    ceos_interfaces:
      config: "{{ceos_interfaces}}"
    when: ceos_interfaces is defined and ceos_interfaces

  - name: Create L3 Interfaces
    ceos_l3_interfaces:
      config: "{{ceos_l3_interfaces}}"
    when: ceos_l3_interfaces is defined and ceos_l3_interfaces

  - name: "Push configs for clos-fabric usecase"
    vars:
      ansible_connection: network_cli
    ceos_config:
      src: clos_fabric_cfg.j2
    register: result

  - name: Create BGP configuration
    ceos_bgp:
      config: "{{ceos_bgp}}"
    when: ceos_bgp is defined and ceos_bgp

  - name: Create BGP AF configuration
    ceos_bgp_af:
      config: "{{ceos_bgp_af}}"
    when: ceos_bgp_af is defined and ceos_bgp_af

  - name: Create BGP Neighbors configuration
    ceos_bgp_neighbors:
      config: "{{ceos_bgp_neighbors}}"
    when: ceos_bgp_neighbors is defined and ceos_bgp_neighbors

  - name: Create BGP Neighbors AF configuration
    ceos_bgp_neighbors_af:
      config: "{{ceos_bgp_neighbors_af}}"
    when: ceos_bgp_neighbors_af is defined and ceos_bgp_neighbors_af