---
- hosts: poc_mgmt
  connection: network_cli
  gather_facts: No
  collections:
     - dellemc.os10

  tasks:
  - name: "CFGGEN: Generating the Vxlan Cleanup Configuration"
    template:
        src: no_vxlan.j2
        dest: "{{ build_dir }}/os10_clean_vxlan_{{hostname}}.conf.part"
    when: (ansible_network_os is defined and ansible_network_os == "dellos10") and ((dellos_cfg_generate | default('False')) | bool)
  #   notify: save config os10
  #   register: generate_output
    tags:
      - novxlan
      - cfggen

  - name: "CFGGEN: Generating the Underlay Cleanup Configuration"
    template:
        src: no_underlay.j2
        dest: "{{ build_dir }}/os10_clean_underlay_{{hostname}}.conf.part"
    when: (ansible_network_os is defined and ansible_network_os == "dellos10") and ((dellos_cfg_generate | default('False')) | bool)
  #   notify: save config os10
  #   register: generate_output
    tags:
      - nounderlay
      - cfggen

  - name: "CFGGEN: Generating Vxlan configuration"
    template:
        src: dellos10_vxlan.j2
        dest: "{{ build_dir }}/os10_vxlan_{{hostname}}.conf.part"
    when: (ansible_network_os is defined and ansible_network_os == "dellos10") and ((dellos_cfg_generate | default('False')) | bool)
  #   notify: save config os10
  #   register: generate_output
    tags:
      - vxlan
      - cfggen

  - name: "CFGPUSH: Cleaning Vxlan configuration"
    os10_config:
        src: no_vxlan.j2
    when: (ansible_network_os is defined and ansible_network_os == "dellos10")
  #   notify: save config os10
  #   register: output
    tags:
      - novxlan
      - cfgpush

  - name: "CFGPUSH: Cleaning Underlay configuration"
    os10_config:
        src: no_underlay.j2
    when: (ansible_network_os is defined and ansible_network_os == "dellos10")
  #   notify: save config os10
  #   register: output
    tags:
      - nounderlay
      - cfgpush

  - name: "CFGPUSH: Provisioning VXLAN configuration"
  #   debugger: on_failed
    os10_config:
        src: dellos10_vxlan.j2
        save: "yes"
    when: (ansible_network_os is defined and ansible_network_os == "dellos10")
  #   notify: save config os10
    register: output
    tags:
      - vxlan
      - cfgpush
