---
- hosts: ceos
  gather_facts: false
  collections:
  - arista.eos

  tasks:
  - name: Generate the templated config
    template:
      src: ceos/bgp_overlay_ibgp.j2
      dest: "{{ build_dir }}/{{hostname}}.conf.part"
    delegate_to: localhost
    tags:
    - cfggen

  - name: Display the generated config
    debug: var=item
    with_file:
    - "{{ build_dir }}/{{hostname}}.conf.part"
    tags:
    - cfggen

  - name: Generate the templated config
    eos_config:
      src: ceos/bgp_overlay_ibgp.j2
    tags:
    - cfgpush
