---
- hosts: dc1
  connection: network_cli
  gather_facts: no
  any_errors_fatal: True

  tasks:
  - name : "Remove BGPv4 Config"
    eos_config:
      lines:
        - "no router bgp {{ bgp.local_as }}"
    tags:
      - nobgp

  - name : "Shutdown the BGPv4 Peer"
    eos_config:
      lines:
        - "shutdown"
        - 
      parents: ['router bgp {{ bgp.local_as }}']
      match: exact
      # prompt: "[confirm]"
      # answer: "yes"
    notify:
    - display BGP info
    tags:
      - bgpdown

  - name : "Bringup the BGPv4 Peer"
    eos_config:
      lines:
        - "no shutdown"
      parents: ['router bgp {{ bgp.local_as }}']
      match: exact
    notify:
      - display BGP info
    tags:
      - bgpup

  - name: Wait 15 secs for BGP Peers coming up
    pause:
      seconds: 15
    delegate_to: localhost
    when: peerstate == "up"
 
  handlers:
    - name: collect BGP status
      eos_command:
        commands: "{{ item }}"
      with_items:
        - 'show ip bgp summary'
      register: output  

    - name: display BGP info
      debug: 
        var: "{{ item }}"
      with_items:
        - output.results[0].stdout_lines
