---
- hosts: poc_gateway
  gather_facts: false

  tasks:
  - name: Generate the templated config
    template:
      src: ceos/frr.j2
      dest: "files/frr.conf.{{hostname}}"
    delegate_to: localhost
    tags:
    - cfggen

  - name: Display the generated config
    debug: var=item
    with_file:
    - "files/frr.conf.{{hostname}}"
    tags:
    - cfggen
