---
- hosts: poc_gateway
  gather_facts: false

  tasks:
  - name: Generate the templated config
    template:
      src: ceos/vrf_intf.j2
      dest: "topology/cfg/frr.conf.{{hostname}}"
    delegate_to: localhost
    tags:
    - cfggen

  - name: Display the generated config
    debug: var=item
    with_file:
    - "topology/cfg/frr.conf.{{hostname}}"
    tags:
    - cfggen
