---
- hosts: poc_leaf
  gather_facts: no
  # serial: 1
  any_errors_fatal: True

  tasks:
    - name: Get Current OS Version
      dellos10_facts:
        gather_subset: hardware
      register: pre_facts

    - block:
      - name : Reload from standby partition
        dellos10_command:
          commands:
              - write mem
              - boot system standby
              - command: 'reload'
                prompt: 'Proceed to reboot'
                answer: 'y'
      
      - name: Wait for to reload
        wait_for:
          host: "{{ ansible_host }}"
          port: 22
          delay: 10
          timeout: 600
      
      - name: Wait 1min for to start traffic
        pause:
          minutes: 1
        delegate_to: localhost

      - name: Get new facts 
        dellos10_facts:
          gather_subset: hardware
        register: post_facts
      
      - name: Verify OS is upgraded
        assert:
          that:
            - dellos_image_upgrade.software_version == post_facts.ansible_facts.ansible_net_version
          fail_msg: "switch {{inventory_hostname}} is still on OS version: {{post_facts.ansible_facts.ansible_net_version}}"
        
    # ony reload if switch is on different os version and image install was successful
      when: dellos_image_upgrade.software_version != pre_facts.ansible_facts.ansible_net_version
