---
- hosts: poc_leaf
  connection: network_cli
  gather_facts: no
  any_errors_fatal: True
  collections:
    - dellemc.enterprise_sonic
    - dellemc.os10

  tasks:
  - name: Get Current OS Version
    dellos10_facts:
      gather_subset: hardware
    register: pre_facts
    tags: version

  - debug: var=pre_facts.ansible_facts.ansible_net_version
    tags: version

  - name : Reloading OS10 to ONIE OS Uninstall
    dellos10_command:
      commands:
          - command: 'reload onie uninstall'
            prompt: ':'
            answer: 'yes'
    tags: reload_onie

  - name: Pause 25 Mins for switches ONIE Uninstall/Reinstall NOS
    pause:
      minutes: 25
      prompt: "Waiting ZTP Procedure completing ..."
    tags: waitfor


  - name: Wait upto 15 mins for switches ready
    wait_for:
      host: "{{ ansible_host }}"
      port: 22
      delay: 30
      timeout: 900
    tags: waitfor

  - name: Pause 3 Mins for switches fully ready
    pause:
      minutes: 3
      prompt: "Pause 3 Mins for switches fully ready ..."
    tags: waitfor

  - name: Get Current OS Version
    dellos10_facts:
      gather_subset: hardware
    register: pre_facts
    tags: waitfor
    when: (ansible_network_os is defined and ansible_network_os == "dellos10") and ((dellos_cfg_generate | default('False')) | bool)

  - debug: var=pre_facts
    when: (ansible_network_os is defined and ansible_network_os == "dellos10") and ((dellos_cfg_generate | default('False')) | bool)

  - name: "Gather facts"
    sonic_facts:
      gather_subset: min
      gather_network_resources: 
        - interfaces
        - l3_interfaces
        # - lag_interfaces
        # - vlans
        - bgp
    register: result
    when: (ansible_network_os is defined and ansible_network_os == "dellemc.enterprise_sonic.sonic")

  - name: "debug facts"
    debug: 
      msg: "{{ result.ansible_facts.ansible_network_resources }}"
    when: (ansible_network_os is defined and ansible_network_os == "dellemc.enterprise_sonic.sonic")
    