# - name: Block specific IP
#   iptables:
#     chain: INPUT
#     source: 8.8.8.8
#     jump: DROP
#   become: yes

# - name: Forward port 80 to 8600
#   iptables:
#     table: nat
#     chain: PREROUTING
#     in_interface: eth0
#     protocol: tcp
#     match: tcp
#     destination_port: 80
#     jump: REDIRECT
#     to_ports: 8600
#     comment: Redirect web traffic to port 8600
#   become: yes

# - name: Allow related and established connections
#   iptables:
#     chain: INPUT
#     ctstate: ESTABLISHED,RELATED
#     jump: ACCEPT
#   become: yes

# - name: Allow new incoming SYN packets on TCP port 22 (SSH)
#   iptables:
#     chain: INPUT
#     protocol: tcp
#     destination_port: 22
#     ctstate: NEW
#     syn: match
#     jump: ACCEPT
#     comment: Accept new SSH connections.

- name: Allow ICMPv4
  iptables:
    chain: "{{ item }}"
    protocol: icmp
    ip_version: ipv4
    jump: ACCEPT
  with_items: [INPUT, FORWARD, OUTPUT]
  become: yes
  tags:
    - iptable

- name: Allow ICMPv6
  iptables:
    chain: "{{ item }}"
    protocol: icmp
    ip_version: ipv6
    jump: ACCEPT
  with_items: [INPUT, FORWARD, OUTPUT]
  become: yes
  tags:
    - iptable
  
- name: Allow related and established connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: yes
  tags:
    - iptable

- name: Allow IPv4 All
  iptables:
    chain: "{{ item }}"
    ip_version: ipv4
    jump: ACCEPT
  with_items: [INPUT, FORWARD, OUTPUT]
  become: yes
  tags:
    - iptable

- name: Allow IPv6 All
  iptables:
    chain: "{{ item }}"
    ip_version: ipv6
    jump: ACCEPT
  with_items: [INPUT, FORWARD, OUTPUT]
  become: yes
  tags:
    - iptable
