---
# tasks file for dellos10

 - name: "Generating Layer2 Interface Profile for dellos10"
   template:
      src: intf_module.j2
      dest: "{{ build_dir }}/intf_{{hostname}}.conf.part"
   when: (ansible_network_os is defined and ansible_network_os == "dellos10") and ((dellos_cfg_generate | default('False')) | bool)
#   notify: save config os10
   register: generate_output
   tags:
    - layer2
    - cfggen

 - name: "Provisioning Layer2 Interface Profile for dellos10"
   dellos10_config:
      src: intf_module.j2
   when: (ansible_network_os is defined and ansible_network_os == "dellos10")
#   notify: save config os10
   register: output
   tags:
    - layer2


