---
# tasks file for Dell-Networking.dellos-system
 
 - name: "Generating Domain configuration for dellos10"
   template:
      src: dellos10_domain.j2
      dest: "{{ build_dir }}/domain_{{hostname}}.conf.part"
#   notify: save config os10
   register: generate_output
   tags:
    - sysserv
    - cfggen

 - name: "Provisioning Domain configuration for dellos10"
   dellos10_config:
      src: dellos10_domain.j2
   when: (ansible_network_os is defined and ansible_network_os == "dellos10")
#   notify: save config os10
   register: output
   tags:
    - sysserv


