---
# tasks file for Dell-Networking.dellos-system
 
 - name: "Generating NTP configuration for dellos10"
   template:
      src: dellos10_ntp.j2
      dest: "{{ build_dir }}/ntp_{{hostname}}.conf.part"
   when: (ansible_network_os is defined and ansible_network_os == "dellos10") and ((dellos_cfg_generate | default('False')) | bool)
#   notify: save config os10
   register: generate_output
   tags:
    - sysserv
    - cfggen

 - name: "Enable NTP under VRF"
   vars:
      ansible_command_timeout: 60
   dellos10_config:
      commands: 
       - command: ntp enable vrf {{ ntp.vrf }}
         prompt: ":"
         answer: "yes"
   register: output
   tags:
    - sysserv

 - name: "Provisioning NTP configuration for dellos10"
   dellos10_config:
      src: dellos10_ntp.j2
   when: (ansible_network_os is defined and ansible_network_os == "dellos10")
#   notify: save config os10
   register: output
   tags:
    - sysserv


